/* -----------------------------------------------------------------------------
GLEAM/AE                  Sprach-Header-File (Englisch) 
Package: ched                    File: ched_gb.h             Version:     V1.0.5
Status : o.k.                   Autor: W.Jakob                 Datum: 07.08.2020
--------------------------------------------------------------------------------
This is free software, which is governed by the Lesser GNU Public Licence (LGPL), 
version 3, see the comment section at the end of the main program files or the 
files "schalter.h".
-------------------------------------------------------------------------------- */


/* ----------------------- Texte des Moduls: ch_ausg --------------------------- */
#define NO_SUB_AK     "No subchain."
#define KEIN_ELEM_TXT "%3d. element: NIL pointer received!"
#define UNTER_AK_TXT  "AC reference = %s"
#define LOK_UAK_TXT   "Local SubAC of length %d"
#define BAD_UAK_TXT   "Invalid subchain! refCode=%d"
#define PUFFER_TXT    "buffer"
#define VERW_TXT      "administration"
#define AKTIONS_TXT   ""
#define X_KETTE_TXT   "%sChromosome %s of length %d:"
#define HDR_DATA_TXT  "Header data:"
#define NIX_NOTE_TXT  "no fitness"
#define HDR_ZEILE_TXT "  fitness=%s  simu=%s  refs=%d  state=%u  segm=%d"
#define BAD_HDR_TXT   "%s.: In %s wrong header: %1d"
#define BAD_CODE_TXT  "%s.: Unknown activity code: %1d"
#define BAD_CODE_TXT2 "Unknown! Code: %1d"
#define NIX_CH_TXT    "ZEIGE_KETTE: NIL-pointer received!"
#define AUSG_HDR_TXT  "                          Chain Display:"
#define AUSG_QUERY    "Output to s=screen, f=file, ESC=abort.  Select [s]: "
#define SCREEN_CHAR   'S'
#define FILE_CHAR     'F'
#define START_QUERY   "Enter start index (0=Hdr..%1d) [0]: "
#define END_QUERY     "Enter end index (0=Hdr..%1d)   [%1d]: "
#define NIX_DA_TXT    "   There is nothing to be shown!"
#define ABSCHL_TXT    "File \"%s\" written."

/* ---------------------- Texte des Moduls: c_ch_edi --------------------------- */
#define CHAIN_LOADED  "Chain loaded:"
#define NO_WORK_CHAIN "No work chain loaded!"
#define EMPTY_CHAIN   "The chain is empty!"
#define AK_LOE_QUERY1 "Delete work chain "
#define AK_LOE_QUERY2 " "JA_NEIN_TXT
#define NO_AK_NO_SEGM "No AC! -> chain remains unsegmented!"
#define SUB_AK_IN_USE "Subchain is already in use!"
#define CHOOSE_SUB_AK "Select subchain:"
#define BAD_SUB_CH    "Warning: Subchain does not fit to "
#define ELEM_DEL_TXT  "%d. action \"%s\" deleted."
#define PUF_ANZG_HDR  "          Editor Buffers:"
#define PUF_ANZG_KOPF "buffer chain type  address   length"
#define PUF_LEER_TXT  "      empty"
#define PUFFER_I_TXT  "buffer%c"
#define SEGMANZG_KOPF "                        Chain Segmentation:"
#define SEGM_ANZ_TXT  "The chain has %1u segments."
#define SEGMANZG_HDR1 "segm  segment start              segment end"
#define SEGMANZG_HDR2 "  no  ElNo element-name          ElNo element-name"
#define CHED_TXT1     "                           Chain-Editor"
#define CHED_TXT2     "        All unstored chains contained in the editor buffers"
#define CHED_TXT3     "         will be lost when terminating the editor session."
#define CHED_TXT4     "                       Version 1.1 for ACs"
#define CHED_MEN_TXT  "ChEditor"
#define CHED_MEN1     "GenItem"
#define CHED_MEN2     "ModItem"
#define CHED_MEN3     "DelItem"
#define CHED_MEN4     "ShowItem"
#define CHED_MEN5     "LoadChain"
#define CHED_MEN6     "StoreChain"
#define CHED_MEN7     "GenChain"
#define CHED_MEN8     "ModHeader"
#define CHED_MEN9     "ShowChain"
#define CHED_MEN10    "ShowSegm"
#define CHED_MEN11    "ShowBuffer"
#define CHED_MEN13    "DefineSegm"
#define CHED_MEN15    "CopySequ"
#define CHED_MEN16    "ShiftSequ"
#define CHED_MEN17    "CopyBuffer"
#define CHED_MEN18    "DelBuffer"
#define CHED_MEN19    "ConcatACs"
#define CHED_MEN21    "NewDefault"
#define CHEDFKT1_TXT1 "                      Setting Default Values:"
#define CHEDFKT1_TXT2 "chain type: A=AC, E=EK, R=RK,"
#define CHEDFKT1_TXT3 "chain type [%s]: "
#define CHEDFKT1_TXT4 "New current "
#define CHEDFKT2_TXT1 "                        %s Initialization:"
#define CHEDFKT4_TXT1 "                            Load Chain:"
#define CHEDFKT4_TXT2 "Chains of this type cannot be loaded!"
#define CHEDFKT5_TXT1 "                   Creation of a Chain Element:"
#define CHEDFKT5_TXT2 "1.Step: selection of an action:"
#define CHEDFKT5_TXT3 "Enter number of action (%1d..%1d): "
#define CHEDFKT5_TXT5 "2.Step: parameterisation of \"%s\":"
#define CHEDFKT5_TXT6 "3.Step: insertion of the new element into the chain:"
#define CHEDFKT5_TXT7 "Behind which element shall the new element be"
#define CHEDFKT5_TXT8 "  inserted? (0..%1d, 0 = direct behind the header)"
#define CHEDFKT5_TXT9 "Element number [%d]: "
#define CHEDFKT5_TXT10 "Element inserted into chain."
#define CHEDFKT6_TXT1 "                          Show Element:"
#define CHEDFKT6_TXT2 "Element number (0..%1d): "
#define CHEDFKT7_TXT1 "Chains of type %s cannot be stored!"
#define CHEDFKT7_TXT2 "                   Storage of %s in buffer %1d:"
#define CHEDFKT7_TXT3 "This chain including possible changes was already been stored! "
#define CHEDFKT7_TXT4 "Multiple storage of one chain is strongly not recomended!"
#define CHEDFKT7_TXT6 "Store chain and delete buffer? "
#define CHEDFKT7_TXT7 "Chain stored. Address: %s"
#define CHEDFKT7_TXT8 "Invalid fitness!"
#define CHEDFKT7_TXT9 "The action chain it not segmented! Unsegmented ACs will in"
#define CHEDFKT7_TXT0 "most cases be ignored during the process of evolution!"
#define CHEDFKT8_TXT1 "                   Modification of an Element:"
#define CHEDFKT8_TXT2 "Element number (1..%1d): "
#define CHEDFKT8_TXT3 "Select new subchain:"
#define CHEDFKT8_TXT5 "Element modified."
#define CHEDFKT9_TXT1 "                   Deletion of a Chain Element:"
#define CHEDFKT9_TXT2 "Element number (1..%1d): "
#define CHEDFKT9_TXT3 "%1d%sdeleted."
#define CHEDFKT10_TXT1 "           Local Editor Buffers:"
#define CHEDFKT10_TXT2 "buffer chain type  address   length"
#define CHEDFKT10_TXT3 "       empty"
#define CHEDFKT10_TXT4 "buffer%c"
#define CHEDFKT11_TXT1 "                Modification of a Chain Header:"
#define CHEDFKT12_TXT1 "                   Display of Chain Segments:"
#define CHEDFKT12_TXT2 "The chain consists of %1u segments."
#define CHEDFKT12_TXT3 "SNo  segment start          segment end"
#define CHEDFKT13_TXT1 "                   Copy of a Chain Sequence:"
#define CHEDFKT13_TXT2 "Start element number (1..%1d): "
#define CHEDFKT13_TXT3 "End element number   (%2d..%1d): "
#define CHEDFKT13_TXT4 "Insertion of the copy behind element (0..%1d): "
#define CHEDFKT13_TXT6 "Copied sequence inserted."
#define CHEDFKT14_TXT1 "                Definition of Chain Segmentation:"
#define CHEDFKT14_TXT2 "This chain is already segmented!"
#define CHEDFKT14_TXT3 "Resegment chain? "JA_NEIN_TXT
#define CHEDFKT14_TXT4 "The chain consists of %1d elements."
#define CHEDFKT14_TXT5 "The segments are defined by typing in their end element numbers."
#define CHEDFKT14_TXT6 "Entering the last chain element terminates input. Pressing ESC"
#define CHEDFKT14_TXT9 "stops input and results in an end segment including the chain end."
#define CHEDFKT14_TXT7 "End of segment #%1d (%1d..%1d): "
#define CHEDFKT14_TXT8 "Segment definition finished."
#define CHEDFKT15_TXT1 "                 Movement of an Element Sequence:"
#define CHEDFKT15_TXT2 "Insertion of the sequence behind element (0..%1d): "
#define CHEDFKT15_TXT4 "Destination is inside of the sequence!"
#define CHEDFKT15_TXT5 "Sequence moved."
#define CHEDFKT16_TXT1 "                       Copy Chain Buffer:"
#define CHEDFKT16_TXT2 "Source "
#define CHEDFKT16_TXT3 "Destination "
#define CHEDFKT16_TXT4 "Chain copied."
#define CHEDFKT16_TXT5 "Error occurred while copying!"
#define CHEDFKT16_TXT6 " cannot be copied!"
#define CHEDFKT17_TXT1 "                    Erasure of Chain Buffer:"
#define CHEDFKT17_TXT2 "Buffer deleted!"
#define CHEDFKT18_TXT1 "         Append a Copy of Source Chain to Destination Chain:"
#define CHEDFKT18_TXT2 "Copy of source chain  successfully appended to destination chain." 
#define CHEDFKT18_TXT3 "Attention: Destination chain may be faulty due to error!"
#define CHEDLCBN_TXT1  "%s buffer number (1..%1d): "
#define CHEDLCBN_TXT2  "%s buffer number (1..%1d) [%1d]: "
#define CHEDLCBN_TXT3  "Invalid chain buffer. Valid range: 1..%1d"
#define AKHDR_MEN_TXT  "Header"
                      /*1234567890*/
#define CHEDPH_TXT1    "Fitness"
#define CHEDPH_TXT2    "State"
#define CHEDPH_TXT3    "SimuValues"
#define CHEDPH_TXT4    "RefCounter"
#define CHEDPH_TXT5    "Update header data:"
#define CHEDPH_TXT6    "Fitness (0..%1ld/%1ld) [%1ld]: "
#define CHEDPH_TXT8    "Chain state [%1ld]: "
#define CHEDPH_TXT9    "%d. value: %s [%.10e]: "
#define CHEDPH_TXT10   "Reference counter [%1d]: "
#define CHEDPH_TXT11   "Header data completed."
#define CHEDPH_TXT12   "Unknown header: No changes!"
#define CHEDDA_TXT1    ".action \"%s\" "
#define CHEDSN_TXT1    "Warning: The segmentation will be defective after execution"
#define CHEDSN_TXT2    "         of this function!"
#define CHEDSN_TXT3    "Perform function? "NEIN_JA_TXT
#define CHEDPBA_TXT1   "empty"
#define CHEDPBA_TXT2   "local"
#define CHEDPBA_TXT3   "Current buffer %1d = %s                 Actual chain type=%s"
#define CHEDFKT100_TXT1 "Exit chain editor? "JA_NEIN_TXT
#define CHEDFKT100_TXT2 "Chain editor terminated!"
