/* -----------------------------------------------------------------------------
GLEAM/AE                  Sprach-Header-File (Deutsch) 
Package: ched                    File: ched_d.h              Version:     V1.0.4
Status : o.k.                   Autor: W.Jakob                 Datum: 03.05.2016
--------------------------------------------------------------------------------
This is free software, which is governed by the Lesser GNU Public Licence (LGPL), 
version 3, see the comment section at the end of the main program files or the 
files "schalter.h".
-------------------------------------------------------------------------------- */


/* ----------------------- Texte des Moduls: ch_ausg --------------------------- */
#define NO_SUB_AK     "Keine Unterkette."
#define KEIN_ELEM_TXT "%3d. Element: Nil-Pointer erhalten!"
#define UNTER_AK_TXT  "AK-Referenz = %s"
#define LOK_UAK_TXT   "Lokale Unter-AK der L"ae"nge %d"
#define BAD_UAK_TXT   "Unzul"ae"ssige Unterkette. RefCode=%d"
#define PUFFER_TXT    "Puffer"
#define VERW_TXT      "Verwaltungs"
#define AKTIONS_TXT   "Aktions"
#define X_KETTE_TXT   "%sKette %s der L"ae"nge %d:"
#define HDR_DATA_TXT  "Kopfdaten:"
#define NIX_NOTE_TXT  "KeineNote"
#define HDR_ZEILE_TXT "  Fitness=%s  Simu=%s  Refs=%d  Stat=%u  Segm=%d"
#define BAD_HDR_TXT   "%s.: In %s falscher Hdr: %1d"
#define BAD_CODE_TXT  "%s.: Unbekannter activity-Code: %1d"
#define BAD_CODE_TXT2 "Unbekannt! Code: %1d"
#define NIX_CH_TXT    "ZEIGE_KETTE: Nil-Pointer erhalten!"
#define AUSG_HDR_TXT  "                          Kettenausgabe:"
#define AUSG_QUERY    "Ausgabe auf B=Bildschirm, F=File, ESC=Abbruch.  Auswahl [B]: "
#define SCREEN_CHAR   'B'
#define FILE_CHAR     'F'
#define START_QUERY   "Startindex eingeben (0=Hdr..%1d) [0]: "
#define END_QUERY     "Endindex eingeben (0=Hdr..%1d)   [%1d]: "
#define NIX_DA_TXT    "   Es ist nichts zum Anzeigen da!"
#define ABSCHL_TXT    "File \"%s\" geschrieben."

/* ---------------------- Texte des Moduls: c_ch_edi --------------------------- */
#define CHAIN_LOADED  "Kette geladen:"
#define NO_WORK_CHAIN "Keine Arbeitskette geladen!"
#define EMPTY_CHAIN   "Die Kette ist leer!"
#define AK_LOE_QUERY1 "Arbeitskette "
#define AK_LOE_QUERY2 " l"oe"schen "JA_NEIN_TXT
#define NO_AK_NO_SEGM "Keine AK! -> Kette ist unsegmentiert!"
#define SUB_AK_IN_USE "Unterkette wird bereits benutzt!"
#define CHOOSE_SUB_AK "Unterkette ausw"ae"hlen:"
#define BAD_SUB_CH    "Warnung: Subkette pa"ss"t nicht zur "
#define ELEM_DEL_TXT  "%d. Aktion \"%s\" gel"oe"scht."
#define PUF_ANZG_HDR  UE"bersicht "ue"ber den Pufferspeicher:"
#define PUF_ANZG_KOPF "Puffer  Kettenart  Adresse   L"ae"nge"
#define PUF_LEER_TXT  "       leer"
#define PUFFER_I_TXT  "Puffer%c"
#define SEGMANZG_KOPF "                 Anzeige der Kettensegmentierung:"
#define SEGM_ANZ_TXT  "Die Kette hat %1u Segmente."
#define SEGMANZG_HDR1 "Segm  Segmentanfang              Segmentende"
#define SEGMANZG_HDR2 "  Nr  E-Nr Element-Name          E-Nr Element-Name"
#define CHED_TXT1     "                          Ketten-Editor"
#define CHED_TXT2     "           Bei der Beendigung mit ESC gehen alle nicht "
#define CHED_TXT3     "           gespeicherten Ketten in den Puffern verloren."
#define CHED_TXT4     "                       Version 1.1 f"ue"r AKs"
#define CHED_MEN_TXT  "KetEditor"
#define CHED_MEN1     "GenElement"
#define CHED_MEN2     "ModElement"
#define CHED_MEN3     "L"oe"Element "
#define CHED_MEN4     "ZeigElem"
#define CHED_MEN5     "LadeKette"
#define CHED_MEN6     "RetteKette"
#define CHED_MEN7     "GenKette"
#define CHED_MEN8     "ModKopf"
#define CHED_MEN9     "ZeigeKette"
#define CHED_MEN10    "ZeigeSegm"
#define CHED_MEN11    "ZeigPuffer"
#define CHED_MEN13    "SetzeSegm"
#define CHED_MEN15    "KopiereSeq"
#define CHED_MEN16    "SchiebeSeq"
#define CHED_MEN17    "KopierePuf"
#define CHED_MEN18    "L"oe"schePuf "
#define CHED_MEN19    "KonkatAKs"
#define CHED_MEN21    "NeuDefault"
#define CHEDFKT1_TXT1 "                     Defaultwerte einstellen:"
#define CHEDFKT1_TXT2 "Kettenarten: A=AK, E=EK, R=RK,"
#define CHEDFKT1_TXT3 "Kettenart [%s]: "
#define CHEDFKT1_TXT4 "Neue aktuelle "
#define CHEDFKT2_TXT1 "                       %s-Initialisierung:"
#define CHEDFKT4_TXT1 "                           Lade Kette:"
#define CHEDFKT4_TXT2 "Ketten dieser Art sind nicht ladbar!"
#define CHEDFKT5_TXT1 "                 Erzeugung eines Kettenelements:"
#define CHEDFKT5_TXT2 "1.Schritt: Auswahl einer Aktion:"
#define CHEDFKT5_TXT3 "Aktionsnummer eingeben (%1d..%1d): "
#define CHEDFKT5_TXT5 "2.Schritt: Parametrierung von \"%s\":"
#define CHEDFKT5_TXT6 "3.Schritt: Neues Element in die Kette h"ae"ngen:"
#define CHEDFKT5_TXT7 "Hinter welchem Element soll das neue Element eingef"ue"gt "
#define CHEDFKT5_TXT8 "  werden? (0..%1d, 0 = Direkt hinter dem Header)"
#define CHEDFKT5_TXT9 "Elementnummer [%d]: "
#define CHEDFKT5_TXT10 "Element in die Kette eingef"ue"gt."
#define CHEDFKT6_TXT1 "                          Zeige Element:"
#define CHEDFKT6_TXT2 "Elementnummer (0..%1d): "
#define CHEDFKT7_TXT1 "Kette vom Typ %s nicht speicherbar!"
#define CHEDFKT7_TXT2 "                 Speichern der %s in Puffer %1d:"
#define CHEDFKT7_TXT3 "Diese Kette ist mit eventuellen "AE"nderungen bereits gespeichert!"
#define CHEDFKT7_TXT4 "Von einer Mehrfachspeicherung wird dringend abgeraten!"
#define CHEDFKT7_TXT6 "Speichern u.Puffer l"oe"schen? "
#define CHEDFKT7_TXT7 "Kette gespeichert. Adresse: %s"
#define CHEDFKT7_TXT8 "Ung"ue"ltige Note (Fitness)!"
#define CHEDFKT7_TXT9 "Die AK ist nicht segmentiert! Unsegmentierte AKs werden bei der"
#define CHEDFKT7_TXT0 "Evolution in der Regel ignoriert!"
#define CHEDFKT8_TXT1 "                   Modifikation eines Elements:"
#define CHEDFKT8_TXT2 "Elementnummer (1..%1d): "
#define CHEDFKT8_TXT3 "Neue Unterkette ausw"ae"hlen:"
#define CHEDFKT8_TXT5 "Element modifiziert."
#define CHEDFKT9_TXT1 "                  L"oe"schung eines Kettenelements:"
#define CHEDFKT9_TXT2 "Elementnr (1..%1d): "
#define CHEDFKT9_TXT3 "%1d%sgel"oe"scht."
#define CHEDFKT10_TXT1 "                 "UE"bersicht "ue"ber den Pufferspeicher:"
#define CHEDFKT10_TXT2 "Puffer  Kettenart  Adresse   L"ae"nge"
#define CHEDFKT10_TXT3 "       leer"
#define CHEDFKT10_TXT4 "Puffer%c"
#define CHEDFKT11_TXT1 "                 Modifikation des Kettenkopfs:"
#define CHEDFKT12_TXT1 "                  Anzeige der Kettensegmente:"
#define CHEDFKT12_TXT2 "Die Kette hat %1u Segmente."
#define CHEDFKT12_TXT3 "SNr  Segmentanfang          Segmentende"
#define CHEDFKT13_TXT1 "                  Kopieren einer Element-Sequenz:"
#define CHEDFKT13_TXT2 "Anfangselementnr ( 1..%1d): "
#define CHEDFKT13_TXT3 "Endelementnr     (%2d..%1d): "
#define CHEDFKT13_TXT4 "Einf"ue"gen der Kopie hinter Element (0..%1d): "
#define CHEDFKT13_TXT6 "Kopierte Sequenz eingef"ue"gt."
#define CHEDFKT14_TXT1 "                Eingabe der Kettensegmentierung:"
#define CHEDFKT14_TXT2 "Die AK ist bereits segmentiert!"
#define CHEDFKT14_TXT3 "Kette neu segmentieren? "JA_NEIN_TXT
#define CHEDFKT14_TXT4 "Die Kette hat %1d Elemente."
#define CHEDFKT14_TXT5 "Nachfolgend werden die Segmentenden eingegeben. Die Eingabe des"
#define CHEDFKT14_TXT6 "letzten Kettenelements beendet den Vorgang. Ein Abbruch durch "
#define CHEDFKT14_TXT9 "ESC bewirkt, da"szt" das letzte Segment bis zum Kettenende reicht."
#define CHEDFKT14_TXT7 "Ende des %1d.Segements (%1d..%1d): "
#define CHEDFKT14_TXT8 "Segmenteingabe beendet."
#define CHEDFKT15_TXT1 "               Verschieben einer Element-Sequenz:"
#define CHEDFKT15_TXT2 "Einf"ue"gen der Sequenz hinter Element (0..%1d): "
#define CHEDFKT15_TXT4 "Ziel liegt innerhalb der Sequenz!"
#define CHEDFKT15_TXT5 "Sequenz verschoben."
#define CHEDFKT16_TXT1 "                      Kopiere Kettenpuffer:"
#define CHEDFKT16_TXT2 "Quell-"
#define CHEDFKT16_TXT3 "Ziel-"
#define CHEDFKT16_TXT4 "Kette kopiert."
#define CHEDFKT16_TXT5 "Fehler beim Kopiervorgang!"
#define CHEDFKT16_TXT6 " nicht kopierbar!"
#define CHEDFKT17_TXT1 "                      L"oe"sche Kettenpuffer:"
#define CHEDFKT17_TXT2 "Puffer gel"oe"scht!"
#define CHEDFKT18_TXT1 "           Kopie der Quellkette an Zielkette anh"ae"ngen:"
#define CHEDFKT18_TXT2 "Kopie der Quellkette erfolgreich an Zielkette angeh"ae"ngt." 
#define CHEDFKT18_TXT3 "Vorsicht: Zielkette wegen Fehler wahrscheinlich fehlerhaft!"
#define CHEDLCBN_TXT1  "%sKettenpuffer-Nummer (1..%1d): "
#define CHEDLCBN_TXT2  "%sKettenpuffer-Nummer (1..%1d) [%1d]: "
#define CHEDLCBN_TXT3  "Unzul"ae"ssiger Kettenpuffer. G"ue"ltig: 1..%1d"
#define AKHDR_MEN_TXT  "Kopfdaten"
                      /*1234567890*/
#define CHEDPH_TXT1    "Fitness"
#define CHEDPH_TXT2    "Status"
#define CHEDPH_TXT3    "SimuWerte"
#define CHEDPH_TXT4    "RefCounter"
#define CHEDPH_TXT5    "Vorgabe von Headerdaten:"
#define CHEDPH_TXT6    "Fitness (0..%1ld/%1ld) [%1ld] "
#define CHEDPH_TXT8    "Kettenstatus [%1ld]: "
#define CHEDPH_TXT9    "%d. Wert: %s [%.10e]: "
#define CHEDPH_TXT10   "Referenzz"ae"hler [%1d]: "
#define CHEDPH_TXT11   "Headerdatenvorgabe beendet."
#define CHEDPH_TXT12   "Unbekannter Header: Nichts "ae"nderbar!"
#define CHEDDA_TXT1    ".Aktion \"%s\" "
#define CHEDSN_TXT1    "Warnung: Die Segmentierung wird nach Ausf"ue"hrung dieser Funktion"
#define CHEDSN_TXT2    "         fehlerhaft sein!"
#define CHEDSN_TXT3    "Funktion ausf"ue"hren "NEIN_JA_TXT
#define CHEDPBA_TXT1   "leer"
#define CHEDPBA_TXT2   "lokal"
#define CHEDPBA_TXT3   "Aktueller Puffer %1d = %s           Aktuelle Kettenart=%s"
#define CHEDFKT100_TXT1 "Ketten-Editor beenden? "JA_NEIN_TXT
#define CHEDFKT100_TXT2 "Ketten-Editor beendet!"

