/* -----------------------------------------------------------------------------
GLEAM/AE                  Sprach-Header-File (Deutsch)                          
Package: bew                     File: bew_d.h               Version:     V1.4.1
Status : o.k.                   Autor: W.Jakob                 Datum: 16.09.2020
--------------------------------------------------------------------------------
This is free software, which is governed by the Lesser GNU Public Licence (LGPL), 
version 3, see the comment section at the end of the main program files or the 
files "schalter.h".
-------------------------------------------------------------------------------- */

/* ----------------------- Texte des Moduls: bewert ------------------------- */
#define GNU_LABEL1N    "' title 'Ungew. Fitness' with lines lc rgbcolor \"#b600b6\" lw 1.5"
#define GNU_LABEL1S    "' title 'Straffaktor' with lines lc rgbcolor \"#b600b6\" lw 1.5"
#define GNU_LABEL2A    "' title 'St"ue"tzpunkte'"
#define GNU_LABEL2B    "' title 'XDrittel'"
#define GNU_LABEL2C    "' title 'St"ue"tzpunkte'"
#define GNU_LABEL3     "' title 'Erf"ue"llungswert' with impulses lc rgbcolor \"#00ee00\" lw 1.6"  /* lc 9 lw 2 */
#define GNU_IP_COL     " with impulses lc rgbcolor \"#dd0000\""
#define GNU_NOTE_TXT   "Fitness [Tsd]"
#define GNU_STRAF_TXT  "Straffaktor"
#define BEW_FKT_TXT    "Bewertungs"
#define STR_FKT_TXT    "Straf"
#define BEW_FILE_HDR_1 "Bewertungsbeschreibung fuer GLEAM/AE               %s\n"
#define BEW_FILE_HDR_2 "%3d %3d       Anzahl der aktiven und benutzten Kriterien von insgesamt %2d.\n"
#define BEW_FILE_STRFF "------------ Straffunktionen: ------------ \n"
#define BEW_FILE_END_1 "Daten pro Eintrag (KRITERIUMS_TYP):\n"
#define BEW_FILE_END_2 "  Name mit \":\" (max %d Zeichen)\n"
#define BEW_FILE_END_3 "  Einheit: Kriterien: Standard-Einheitsbezeichner (\" \"=leer).\n"
#define BEW_FILE_END_4 "           StrafFkt:  Einheitsbezeichner bei Bereichsueberschreitung:\n"
#define BEW_FILE_END_5 "                         <flag><blank><bezeichner>\n"
#define BEW_FILE_END_6 "                      flag = !: leer\n"
#define BEW_FILE_END_7 "                             <: 2.Ausgabe des 1000-fachen Werts\n"
#define BEW_FILE_END_8 "                             >: 2.Ausgabe des 1/1000 des Werts\n"
#define BEW_FILE_END_9 "                             %%: 2.Ausgabe im G-Format, wenn Wert < 1.0 oder Wert >= 100000\n"
#define BEW_FILE_END10 "  klasse  max_note  erfuellungs_wert\n"
#define BEW_FILE_END11 "  bew_alg   nstart ns1 ns2 nend   nmax_cont\n"
#define BEW_FILE_END12 "            xstart xs1 xs2 xend   xdrittel\n"


/* ----------------------- Texte des Moduls: bew_gsw ------------------------ */
#define NOTEN_HDR1    "                          Bewertungskriterien:"
#define NOTEN_HDR2    "Nr. Kriterium           Prio-      Noten-    Erf"ue"llungs-   StrafFkt Nmax"
#ifdef GUI_MODE
  #define NOTEN_HDR3  "                        Klasse    gewicht    note    wert  PrioKl.  Cont"
#else /* TEXT_MODE or CLV */
  #define NOTEN_HDR3  "                        Klasse     anteil    note    wert  PrioKl.  Cont"
#endif /* TEXT_MODE or CLV */
/*                     xx: 1234567890123456789:tttxxttt (xxxxxx%) xxxxxx xxxxxxx tttxxttt  xxxx*/
#define DEACTIV_TXT   "inaktiv "
#define ZEIG_FKT_TXT1 "Funktionstyp"
#define ZEIG_FKT_TXT2 "und"
#define ZEIG_FKT_TXT3 "Grenzen und St"ue"tzpunkte der Funktion:"
#define ZEIG_FKT_TXT4 "                  x-Wert    Note    [%]"
#define ZEIG_FKT_TXT5 "                  x-Wert  Straffaktor"
#define MINCR_TXT     "monoton steigend"
#define MDECR_TXT     "monoton fallend"
#define LIN_TXT       "linear"
#define EXP_TXT       "exponentiell"
#define NIX_FKT_TXT   "noch nicht definiert!"


/* ----------------------- Texte des Moduls: bew_cmen ----------------------- */
/*                       01234567890123456789:tttxxtt xxxxxx xxxxxx xxxxxxx tttxxtt  xxxx*/
#define XMIN_TXT      "x-Minimum  "
#define XS1_TXT       "x-St"ue"tzpkt1"
#define XS2_TXT       "x-St"ue"tzpkt2"
#define XMAX_TXT      "x-Maximum  "
#define XD_TXT        "x-Drittel  "
#define NS1_TXT       "N-St"ue"tzpkt1"
#define NS2_TXT       "N-St"ue"tzpkt2"
#define STR_S1_TXT    "StrafW-Pkt1"
#define STR_S2_TXT    "StrafW-Pkt2"
#define NKRIT_TXT_01  "Kriterium \"%s\":"
#define NKRIT_TXT_02  "  Info: Aktueller Notenrestwert: %-6ld"
#define NKRIT_TXT_03  "PrioKlasse (0=Deaktivierung)       ["
#define NKRIT_TXT_04  "Notenanteil        (0..%6ld) [%6ld]: "
#define NKRIT_TXT_05  "Erf"ue"llungswert               ["
#define NKRIT_TXT_05A "Ein Erf"ue"llungswert kann erst nach der Definition der zugeh"oe"rigen Bewertungsfunktion vorgegeben werden."
#define NKRIT_TXT_05B "   noch undef."
#define NKRIT_TXT_06  "PrioKlasse d. Straffunktion (0=Aus)[" 
#define NKRIT_TXT_07  "Noten-Summe = %1ld statt %1ld!"
#define NKRIT_TXT_08  "NotenMax bei x-Wert"ue"ber/unterschreitung "
#define NKRIT_TXT_10  "Neue Bezeichnung "
#define NKRIT_TXT_12  "Maximale Laenge: "
#define NKRIT_TXT_13  "Neue Ma"szt"einheit  "
#define NKRIT_TXT_14  "Mit alternativer Ma"szt"einheit       "JA_NEIN_TXT 
#define NKRIT_TXT_15  "Mit alternativer Ma"szt"einheit       "NEIN_JA_TXT
#define NKRIT_TXT_16  "Syntax: \"(<|>) <ma"szt"einheit>\"       "
#define ZEIG_FKT_ABST "    "
#define CHG_FKT_TXT1  "Straffunktion f"ue"r Kriterium \"%s\":"
#define CHG_FKT_TXT2  "Bewertungsfunktion f"ue"r Kriterium \"%s\":"
#define CHG_FKT_TXT3  "Funktionstypen: 1=SteigendLin, 3=SteigendExp, 5=SteigendLinExp,"
#define CHG_FKT_TXT4  "                2=FallendLin,  4=FallendExp,  6=FallendLinExp  "
#define CHG_FKT_TXT5  "Funktionstyp"
#define CHG_FKT_TXT6  "Notenwerte (0..%ld):"
#define CHG_FKT_TXT7  "Werte der Straffunktion (0.0 .. 1.0):"
#define BEW_MENPKT1   "ZeigeKrits"
#define BEW_MENPKT2   AE"nd Krit  "
#define BEW_MENPKT3   "Neues Krit"
#define BEW_MENPKT5   "ZeigBewFkt"
#define BEW_MENPKT6   AE"ndBewFkt "
#define BEW_MENPKT7P  "PlotBewFkt"
#define BEW_MENPKT7T  "TestBewFkt"
#define BEW_MENPKT9   "ZeigStrFkt"
#define BEW_MENPKTA   AE"ndStrFkt "
#define BEW_MENPKTBP  "PlotStrFkt"
#define BEW_MENPKTBT  "TestStrFkt"
#define BEW_MENPKTD   "Plot->File"
#define BEW_MENPKTE   "BeendePlot"
#define MENFKT2_TXT1  "                   "AE"nderung eines Kriteriums:"
#define MENFKT2_TXT2  "Kriterium (1..%2d): "
#define MENFKT2_TXT3  "Kriterium (1..%2d) [%2d]: "
#define MENFKT3_TXT1  "Die maximale Kriterienanzahl von %d ist bereits erreicht!"
#define MENFKT3_TXT2  "               Definition eines neuen Kriteriums:"
#define MENFKT3_TXT3  ""
#define MENFKT3_TXT4  ""
#define MENFKT5_TXT0  "         Anzeige der Parameter einer Bewertungsfunktion:"
#define MENFKT6_TXT1  "        "AE"nderung der Bewertungsfunktion eines Kriteriums:"
#define MENFKT7_TXT1  "           Test der Bewertungsfunktion eines Kriteriums:"
#define MENFKT7_TXT2  "     x-Wert   Note    [%]"
#define MENFKT9_TXT0  "            Anzeige der Parameter einer Straffunktion:"
#define MENFKT9_TXT1  "Kriterium \"%s\" hat keine aktive Straffunktion!"
#define MENFKT10_TXT1 "          "AE"nderung der Straffunktion eines Kriteriums:"
#define MENFKT11_TXT1 "             Test der Straffunktion eines Kriteriums:"
#define MENFKT11_TXT2 "     x-Wert  Straffaktor"
#define MENFKT13_TXT1 "      Hardcopy des letzten Plots"
#define MENFKT13_TXT2 "          (Postscript-File)"
#define MENFKT13_TXT3 "Hardcopy nur nach \"PlotxxxFkt\"m"oe"glich."
#define MENFKT14_TXT1 "           Schlie"szt"e GnuPlot-Fenster"
#define MENFKT14_TXT2 "Kein GnuPlot aktiv"
#define HCPY_MLDG     "Hardcopy in \"%s.ps\"\n"
#define PREP_GNU_TXT1 "Anzahl x-Werte            [%3u]: "
#define PREP_GNU_TXT2 "x-Startwert       [%s]: "
#define PREP_GNU_TXT3 "Delta der x-Werte [%s]: "
#define PREP_GNU_TXT4 "PlotFenster-Nummer (1..%d)   [%d]: "
#define PREP_GNU_KRIT "Kriterium"
#define PREP_GNU_StrF "Straffunktion"
#define NIX_PLOT_TXT  "GNUPlot nicht verf"ue"gbar."
#define NO_CRITS_TXT  "     Die Kriterienliste ist leer!"

